# Generated by Django 5.1.3 on 2024-12-04 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 14, 49, 7, 556151, tzinfo=datetime.timezone.utc)),
        ),
    ]
